export const DEFAULT_GUIDES = [
  {
    id: 'cm-csp-kurulum',
    slug: 'content-manager-csp-kurulumu',
    title: 'Content Manager & CSP (Custom Shaders Patch) Kurulum Rehberi',
    game: 'Assetto Corsa',
    gameCode: 'assetto-corsa',
    category: 'Temel Kurulum',
    forumCategory: 'Assetto Corsa / Temel Kurulum & Araçlar',
    time: '8 dk okuma',
    difficulty: 'Kolay',
    coverImage: '/media/images/cm-csp-preview.jpg',
    summary: 'Assetto Corsa’nın orijinal arayüzünü modern bir simülasyon merkezine dönüştürün. CSP ile dinamik aydınlatma, yağmur ve gelişmiş fizik desteğini devreye alın.',
    highlights: ['Content Manager', 'CSP 0.2.x / 0.1.79', 'Extra FX & Işıklandırma', 'FPS Optimizasyonu'],
    targetPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\assettocorsa',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '9.4k Görüntülenme',
      likes: 512,
      replies: 42,
      date: 'Ekim 2026',
    },
    requirements: [
      'Steam üzerinden orijinal Assetto Corsa (v1.16.4)',
      'Oyunun en az bir kez normal launcher ile açılmış olması',
      'WinRAR veya 7-Zip arşiv programı',
      'Microsoft .NET Framework 4.8 veya üzeri',
    ],
    steps: [
      {
        stepNumber: 1,
        title: 'Content Manager’ı İndirin ve Konumlandırın',
        description: 'Resmi Content Manager sitesinden (acstuff.ru) güncel ZIP arşivini indirin. Arşiv içerisindeki Content Manager.exe dosyasını Assetto Corsa ana oyun klasörüne veya doğrudan Masaüstünüze çıkartın.',
        tip: 'Lite sürüm tamamen ücretsizdir; tek tıkla kurulum için ekstra dosya gerekmez.',
      },
      {
        stepNumber: 2,
        title: 'Oyun ve Steam Yolunu Tanıtın',
        description: 'Content Manager’ı ilk kez çalıştırdığınızda Assetto Corsa kök klasörünü otomatik olarak algılayacaktır. Eğer algılamazsa Steam kütüphanenizdeki "assettocorsa" klasörünü ve Steam oyuncu adınızı seçip onaylayın.',
        tip: 'Steam arka planda açık ve çevrim içi olmalıdır.',
      },
      {
        stepNumber: 3,
        title: 'Custom Shaders Patch (CSP) Eklentisini Yükleyin',
        description: 'Sağ üst köşedeki "Settings" (Ayarlar) sekmesine, ardından "Custom Shaders Patch" sekmesine tıklayın. "About & Updates" menüsünden önerilen en güncel kararlı sürümü (örneğin 0.2.x veya 0.1.79) seçerek "Install" butonuna basın.',
        tip: 'Önerilen sürüm yeşil yıldız veya "Recommended" ibaresiyle belirtilir.',
      },
      {
        stepNumber: 4,
        title: 'Grafik ve Işıklandırma Uzantılarını Açın',
        description: 'CSP ayarları menüsünden "Lighting FX", "Extra FX", "Particles FX" ve "Weather FX" sekmelerini aktif (Active) hale getirin. Bu modüller gece sürüşlerinde gerçekçi far ışıkları, yol aydınlatması ve duman efektlerini sağlar.',
        tip: 'Zayıf ekran kartlarında Extra FX içerisindeki SSLR (Local Reflections) ayarını "Low" tutun.',
      },
      {
        stepNumber: 5,
        title: 'Oyun İçi Video Ayarlarını Yapılandırın',
        description: 'Settings > Assetto Corsa > Video sekmesine giderek çözünürlüğünüzü monitörünüzün yenileme hızına (örn. 1920x1080 @ 144Hz) getirin. Rendering mode olarak "Single Screen" seçildiğinden emin olun.',
        tip: 'MSAA değerini 4x, Anisotropic Filtering değerini 16x yapmak en net görüntüyü verir.',
      },
    ],
    tips: [
      'Content Manager Lite tamamen ücretsizdir. Ancak yapımcıya bağış yaparak anahtar aldığınızda sınırsız sunucu filtreleme ve yedekleme gibi ek özellikler açılır.',
      'FPS kaybı yaşıyorsanız Settings > Custom Shaders Patch > Extra FX menüsünden "Local Reflections (SSLR)" ayarını Medium veya Low seviyesine getirin.',
      'Steam her zaman arka planda açık ve çevrim içi olmalıdır; aksi halde Content Manager oyunu başlatırken hata verebilir.',
    ],
    troubleshooting: [
      {
        problem: 'Can’t patch game executable veya yetki hatası alıyorum.',
        solution: 'Content Manager.exe dosyasına sağ tıklayıp "Yönetici olarak çalıştır" deyin ve Windows Defender/Antivirüs istisnalarına ekleyin.',
      },
      {
        problem: 'Oyuna girerken siyah ekran kalıyor veya oyun çöküyor.',
        solution: 'Settings > Custom Shaders Patch > About & Updates menüsünden bir önceki kararlı CSP sürümüne geri dönmeyi deneyin.',
      },
    ],
    youtubeVideo: {
      id: 'PDVR1IeUS0P',
      title: 'Assetto Corsa Content Manager & CSP Eksiksiz Kurulum Rehberi',
      channel: 'Zecution Gaming Sim Ekibi',
      duration: '11:45',
      description: 'Content Manager arayüzü, Steam dizin bağlantısı ve Custom Shaders Patch grafik uzantılarının adım adım video eşliğinde anlatımı.',
    },
  },
  {
    id: 'pure-rainfx-kurulum',
    slug: 'pure-grafik-modu-ve-rainfx-rehberi',
    title: 'Pure Grafik Modu & Yağmur (Rain FX) Kurulum Rehberi',
    game: 'Assetto Corsa',
    gameCode: 'assetto-corsa',
    category: 'Grafik & CSP',
    forumCategory: 'Assetto Corsa / Grafik Motorları & Hava Durumu',
    time: '12 dk okuma',
    difficulty: 'Orta',
    coverImage: '/media/images/pure-rain-preview.jpg',
    summary: 'Fotogerçekçi gökyüzü dokuları, dinamik 24 saat döngüsü ve camda süzülen gerçekçi yağmur damlaları. Peter Boese Pure motorunun eksiksiz entegrasyonu.',
    highlights: ['Pure 0.27+', 'RainFX Yağmur Modu', 'Pure Config', 'Fotogerçekçi Shaders'],
    targetPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\assettocorsa\\system\\cfg',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '14.2k Görüntülenme',
      likes: 830,
      replies: 68,
      date: 'Ekim 2026',
    },
    requirements: [
      'Content Manager güncel sürüm',
      'Custom Shaders Patch 0.2.x veya CSP Preview (RainFX için Patreon)',
      'Peter Boese Pure v0.27+ arşivi',
      'Temiz bir Assetto Corsa kök klasörü',
    ],
    steps: [
      {
        stepNumber: 1,
        title: 'Eski Sol / Pure Kalıntılarını Temizleyin',
        description: 'Daha önce Sol veya eski Pure sürümü kurduysanız, yeni indirdiğiniz Pure arşivindeki "uninstall pure.bat" ve varsa "uninstall sol.bat" dosyalarını çalıştırarak eski dosyaları temizleyin. Bu işlem çakışmaları %100 önler.',
        tip: 'Arşivden masaüstüne çıkarıp bat dosyasını öyle çalıştırın.',
      },
      {
        stepNumber: 2,
        title: 'Pure Arşiv Dosyalarını Kök Dizine Çıkarın',
        description: 'İndirdiğiniz Pure arşivinin içindeki "apps", "content", "extension" ve "system" klasörlerini doğrudan Assetto Corsa’nın kurulu olduğu ana klasöre kopyalayın ve hedefteki dosyaların değiştirilmesini onaylayın.',
        tip: 'Dosya üzerine yazma uyarısı geldiğinde "Tümünü Değiştir" seçeneğini işaretleyin.',
      },
      {
        stepNumber: 3,
        title: 'Weather FX Scriptini "Pure" Olarak Belirleyin',
        description: 'Content Manager > Settings > Custom Shaders Patch > Weather FX sekmesine gidin. "Weather style" açılır menüsünden "Pure" scriptini seçin. Controller olarak da Pure aktif olmalıdır.',
        tip: 'Controller alanında "pure" seçeneğinin işaretli olduğundan emin olun.',
      },
      {
        stepNumber: 4,
        title: 'RainFX (Yağmur) Özelliğini Etkinleştirin',
        description: 'Yağmur efektlerinin çalışması için CSP Preview (Patreon) sürümü gereklidir. CSP Preview yüklüyse Weather FX menüsünde yağmur fiziği otomatik aktifleşir. Sürüşteyken sağ uygulama çubuğundan "Pure Planner" açıp hava durumunu "Rain" yapabilirsiniz.',
        tip: 'Yağmur damlalarının akışını görmek için sürüş esnasında silecekleri açın.',
      },
      {
        stepNumber: 5,
        title: 'Oyun İçi Pure Config ile Renk Kalibrasyonu',
        description: 'Herhangi bir piste girin, farenizi ekranın en sağına götürerek uygulama çubuğunu açın. "Pure Config" uygulamasını tıklayın. Buradan monitörünüze göre ton haritalama (Tonemapper), pozlama (Exposure) ve kontrastı ayarlayın.',
        tip: 'pureCS veya pureLinear profili en dengeli kontrastı sunar.',
      },
    ],
    tips: [
      'Geceleri yolların gereğinden fazla karanlık veya aydınlık olmaması için Pure Config menüsünde "pureCS" tonemapper profilini seçmeniz tavsiye edilir.',
      'Yağmur damlalarının sileceklerle temizlenmesi için aracın wiper animasyon desteğine sahip olması gerekir.',
    ],
    troubleshooting: [
      {
        problem: 'Gökyüzü tamamen siyah veya mor kareler şeklinde görünüyor.',
        solution: 'Settings > Custom Shaders Patch > Weather FX sekmesinde "Weather style"ın Pure olarak seçildiğinden ve CSP sürümünüzün Pure ile uyumlu olduğundan emin olun.',
      },
      {
        problem: 'Yağmur yağmıyor veya RainFX seçeneği pasif.',
        solution: 'RainFX yalnızca Ilja Jusupov (x4fab) tarafından sunulan CSP Preview sürümlerinde aktiftir. Ücretsiz standart CSP sürümlerinde RainFX motoru bulunmaz.',
      },
    ],
    youtubeVideo: {
      id: 'F4KaTxlNRlF',
      title: 'Assetto Corsa PURE Grafik Modu & Yağmur Kurulumu (2026 Rehberi)',
      channel: 'Zecution Sim Studio',
      duration: '14:20',
      description: 'Peter Boese Pure hava durumu motorunun kurulumu, RainFX ayarları, fotogerçekçi gökyüzü shaderları ve Pure Config kalibrasyonunun canlı gösterimi.',
    },
  },
  {
    id: 'arac-pist-mod-yukleme',
    slug: 'arac-ve-pist-modu-nasil-yuklenir',
    title: 'Assetto Corsa Araç ve Pist Modu Yükleme Rehberi',
    game: 'Assetto Corsa',
    gameCode: 'assetto-corsa',
    category: 'Mod Yükleme',
    forumCategory: 'Assetto Corsa / Araç & Pist Modifikasyonları',
    time: '5 dk okuma',
    difficulty: 'Kolay',
    coverImage: '/media/images/category-assetto-vehicles.jpg',
    summary: 'İndirdiğiniz otomobil, pist ve ses modlarını Content Manager aracılığıyla tek hamlede ya da manuel olarak dosya dizinlerine hatasız yükleyin.',
    highlights: ['Sürükle-Bırak Kurulum', 'Manuel Cars & Tracks Yolu', 'Eksik Ses (FMOD) Çözümü'],
    targetPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\assettocorsa\\content\\cars',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '7.8k Görüntülenme',
      likes: 340,
      replies: 19,
      date: 'Ekim 2026',
    },
    requirements: [
      'Content Manager kurulu olması',
      'İndirilmiş .zip / .rar araç veya pist modu',
      'WinRAR veya 7-Zip',
    ],
    steps: [
      {
        stepNumber: 1,
        title: '1. Yöntem: Content Manager ile Otomatik Yükleme (Önerilen)',
        description: 'İndirdiğiniz .zip veya .rar mod dosyasını açmadan, açık olan Content Manager penceresinin üzerine sürükleyip bırakın. Sağ üstteki yeşil indirme ikonuna tıklayıp "Install" seçeneğine basın.',
        tip: 'Arşiv dosyası şifreli değilse Content Manager saniyeler içinde kurar.',
      },
      {
        stepNumber: 2,
        title: '2. Yöntem: Manuel Araç Modu Kurulumu',
        description: 'Mod arşivini açın. İçerisinde "data.acd", "skins", "ui" gibi klasörler bulunan ana araç klasörünü kopyalayın ve Assetto Corsa’nın "content/cars" klasörüne yapıştırın.',
        tip: 'Klasör içinde aynı isimli alt klasör (çift klasör) olmamasına dikkat edin.',
      },
      {
        stepNumber: 3,
        title: 'Pist / Harita Modu Kurulumu',
        description: 'İndirdiğiniz pist modunu (örneğin Shutoko Revival Project veya Nürburgring) "content/tracks" klasörüne yapıştırın. Pist klasörünün içinde "ui" ve "data" klasörleri olmalıdır.',
        tip: 'Bazı pist modları layout uzantıları içerir, klasör yapısını bozmadan atın.',
      },
      {
        stepNumber: 4,
        title: 'Eksik Motor Sesi veya Fizik Düzeltmesi',
        description: 'Modu yükledikten sonra araçtan ses gelmiyorsa veya oyun çökerse, Content Manager > Content > Cars sekmesinden aracı bulun. Sağ alt menüden "Fix Car Sound" veya "Analyze Data" araçlarını çalıştırın.',
        tip: 'Eski ses bankası kullanan araçlarda Content Manager otomatik ses adaptasyonu yapar.',
      },
    ],
    tips: [
      'Arşivin içinde iç içe klasör olmamalıdır (örn: cars/bmw_e36/bmw_e36 şeklinde değil, doğrudan cars/bmw_e36 şeklinde olmalı).',
      'Türk araç modlarında genellikle özel şifreli data (data.acd) kullanılır; bu dosyayı silmeyin veya değiştirmeyin.',
    ],
    troubleshooting: [
      {
        problem: 'Oyuna girerken "Race Cancelled" hatası verip menüye atıyor.',
        solution: 'Bu hata genellikle aracın şifreli veri dosyası eksik olduğunda ya da pist yüklenemediğinde oluşur. Farklı bir pistte deneme yapın.',
      },
    ],
    youtubeVideo: {
      id: 'gN5hR-h38H8',
      title: 'Assetto Corsa Araba ve Harita Modu Nasıl Yüklenir?',
      channel: 'Zecution Gaming',
      duration: '8:15',
      description: 'Sürükle-bırak yöntemi ile otomatik araç yükleme, manuel dosya dizinleri ve ses gelmeme sorunlarının pratik çözümleri.',
    },
  },
  {
    id: 'beamng-mod-yukleme',
    slug: 'beamng-drive-mod-yukleme-ve-dizin-rehberi',
    title: 'BeamNG.drive Mod Yükleme ve Dizin Rehberi',
    game: 'BeamNG.drive',
    gameCode: 'beamng-drive',
    category: 'Mod Yükleme',
    forumCategory: 'BeamNG.drive / Modifikasyon & Yapılandırma',
    time: '5 dk okuma',
    difficulty: 'Kolay',
    coverImage: '/media/images/game-beamng.jpg',
    summary: 'BeamNG.drive için araç, harita, parça ve ses modlarını doğru kullanıcı dizinine yerleştirin. Mod çakışmalarını ve FPS düşüşlerini önleyin.',
    highlights: ['AppData Dizin Yolu', 'ZIP Ayıklama Yapılmaz', 'Mod Yöneticisi', 'Önbellek Temizleme'],
    targetPath: '%LocalAppData%\\BeamNG.drive\\[surum]\\mods',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '5.1k Görüntülenme',
      likes: 278,
      replies: 15,
      date: 'Ekim 2026',
    },
    requirements: [
      'BeamNG.drive (Güncel v0.33+ sürüm)',
      'İndirilmiş .zip mod dosyası',
    ],
    steps: [
      {
        stepNumber: 1,
        title: 'Önemli Kural: ZIP Dosyalarını Açmayın',
        description: 'BeamNG.drive modları özel bir arşiv yapısına sahiptir. İndirdiğiniz .zip uzantılı mod dosyasını kesinlikle klasöre çıkartmayın veya ayıklamayın; olduğu gibi zip formatında saklayın.',
        tip: 'ZIP dosyasını açmak modun oyunda görünmemesine yol açar.',
      },
      {
        stepNumber: 2,
        title: 'Kullanıcı Veri Klasörünü Açın',
        description: 'Klavyenizdeki Windows + R tuşlarına birlikte basarak "Çalıştır" penceresini açın. Arama kutusuna %localappdata%\\BeamNG.drive\\ yazıp Enter tuşuna basın.',
        tip: 'Doğrudan Windows Çalıştır kutusuna yapıştırabilirsiniz.',
      },
      {
        stepNumber: 3,
        title: 'Güncel Sürüm ve Mods Klasörüne Girin',
        description: 'Karşınıza gelen ekranda oyunun güncel sürüm klasörüne (örneğin 0.33 veya en son sürüm) tıklayın. Klasörün içinde "mods" adında bir klasör bulun veya yoksa sağ tıklayıp "mods" adında yeni bir klasör oluşturun.',
        tip: 'Steam klasörüne değil, kesinlikle AppData altındaki bu klasöre atılmalıdır.',
      },
      {
        stepNumber: 4,
        title: 'Mod Dosyasını Mods Klasörüne Bırakın',
        description: 'İndirdiğiniz .zip mod dosyasını bu "mods" klasörünün içerisine kopyalayın veya sürükleyip bırakın.',
        tip: 'Alt klasör oluşturmadan doğrudan mods/ içine yapıştırın.',
      },
      {
        stepNumber: 5,
        title: 'Oyunda Modu Doğrulayın',
        description: 'BeamNG.drive’ı başlatın. Ana menüden "Mod Yöneticisi" (Mod Manager) sekmesine tıklayın. Yüklediğiniz modun listede göründüğünü ve yanındaki kutucuğun yeşil (aktif) olduğunu doğrulayın.',
        tip: 'Mod listede görünüyorsa Spawn Vehicle ekranında hemen seçebilirsiniz.',
      },
    ],
    tips: [
      'Oyun yeni bir güncelleme aldığında (örn: 0.33’ten 0.34’e), modlarınızı eski sürümün mods klasöründen yeni oluşturulan klasöre taşımanız gerekir.',
      'Çakışan veya oyunu çökerten bir mod olduğunda BeamNG başlatıcısındaki "Support Tools > Clear Cache" (Önbelleği Temizle) butonunu kullanın.',
    ],
    troubleshooting: [
      {
        problem: 'Mod oyunda araç listesinde görünmüyor veya eksik parça hatası veriyor.',
        solution: 'ZIP dosyasının bozuk inmediğinden emin olun. Mod çok eski bir BeamNG sürümüne aitse yeni fizik motoruyla uyumsuz olabilir.',
      },
    ],
    youtubeVideo: {
      id: 'Q8Qk6E0p1oI',
      title: 'BeamNG.drive Mod Nasıl Yüklenir? (Dizin Yolu & Mod Yöneticisi)',
      channel: 'BeamNG Rehberleri',
      duration: '7:30',
      description: 'BeamNG.drive kullanıcı dizinini bulma, zip modlarını doğru klasöre atma ve çakışan modları tespit edip temizleme anlatımı.',
    },
  },
  {
    id: 'online-sunucu-rehberi',
    slug: 'assetto-corsa-online-sunucu-ve-hata-cozumleri',
    title: 'Assetto Corsa Online Sunuculara Katılma & Hata Çözümleri',
    game: 'Assetto Corsa',
    gameCode: 'assetto-corsa',
    category: 'Çok Oyunculu',
    forumCategory: 'Assetto Corsa / Çok Oyunculu & Sunucular',
    time: '10 dk okuma',
    difficulty: 'Orta',
    coverImage: '/media/images/category-assetto-servers.jpg',
    summary: 'No Hesi, SRP (Shutoko Revival Project) ve Türk drift/trafik sunucularına katılırken yaşanan "Track Checksum Mismatch", "Car Missing" hatalarının kesin çözümleri.',
    highlights: ['No Hesi & SRP', 'Checksum Hatası Çözümü', 'Sunucu Mod Paketleri', 'Ping Dengeleme'],
    targetPath: 'Content Manager > Drive > Online',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '11.1k Görüntülenme',
      likes: 620,
      replies: 53,
      date: 'Ekim 2026',
    },
    requirements: [
      'Content Manager kurulu olması',
      'Sunucunun gerektirdiği pist ve araç paketleri',
      'Güncel CSP sürümü',
    ],
    steps: [
      {
        stepNumber: 1,
        title: 'Sunucuyu Content Manager’da Bulun',
        description: 'Content Manager > Drive > Online sekmesini açın. Arama kutusuna katılmak istediğiniz topluluğun adını (örneğin "No Hesi", "Shutoko" veya sunucu adını) yazın.',
        tip: 'Yıldız simgesine basarak sunucuyu favorilerinize ekleyebilirsiniz.',
      },
      {
        stepNumber: 2,
        title: 'Kırmızı Uyarıları ve Eksik İçerikleri İnceleyin',
        description: 'Sunucuya tıkladığınızda sağ tarafta araç ve pist bilgileri listelenir. Eğer araç veya pistin yanında kırmızı ünlem simgesi varsa, sunucunun kullandığı mod sizde eksiktir.',
        tip: 'Üzerine tıkladığınızda eksik modun indirme bağlantısı görüntülenebilir.',
      },
      {
        stepNumber: 3,
        title: '"Track Checksum Mismatch" Hatasının Çözümü',
        description: 'Bu hata, sizdeki pist dosyaları ile sunucudaki pist dosyalarının birebir aynı olmadığını gösterir. "content/tracks" klasöründeki eski pist klasörünü tamamen silin ve sunucunun Discord sayfasındaki güncel indirme linkinden pisti sıfırdan kurun.',
        tip: 'Eski pisti silmeden üzerine kopyalamak checksum hatasını düzeltmeyebilir.',
      },
      {
        stepNumber: 4,
        title: '"Car Checksum Mismatch" Hatasının Çözümü',
        description: 'Araç fizik veya data dosyalarında bir değişiklik yapılmışsa bu güvenlik hatası verilir. Aracı silip sunucu paketindeki orijinal araba klasörünü tekrar yükleyin.',
        tip: 'Orijinal mod paketini indirmek için sunucunun Discord #car-pack kanalını kullanın.',
      },
      {
        stepNumber: 5,
        title: 'Doğru Aracı Seçip "Join" Butonuna Basın',
        description: 'Yeşil onay simgesi bulunan uygun (boş) bir araç yuvasına tıklayın. Ekranın sağ alt köşesindeki yeşil "Join" (Katıl) butonuna basarak sunucuya bağlanın.',
        tip: 'Dolu sunucularda "Auto-join when slot opens" kutusunu işaretleyin.',
      },
    ],
    tips: [
      'Kalabalık trafikli sunucularda yüksek FPS elde etmek için CSP > General Patch Settings altındaki "CPU Optimizations" seçeneklerini açık tutun.',
      'Yurtdışı sunucularına bağlanırken anlık ping fırlaması yaşamamak için kablolu (Ethernet) bağlantı tercih edin.',
    ],
    troubleshooting: [
      {
        problem: 'Server is full veya yer kalmadı uyarısı.',
        solution: 'Popüler sunucular çabuk dolar. Sunucu listesinde "Auto-Join when slot opens" özelliğini açarak biri çıktığında otomatik katılabilirsiniz.',
      },
    ],
    youtubeVideo: {
      id: 'G43oGxEvC0C',
      title: 'Assetto Corsa Online Sunuculara Katılma & Checksum Hatası Çözümü',
      channel: 'Zecution Gaming Sunucu Ekibi',
      duration: '12:50',
      description: 'Shutoko ve No Hesi sunucularına bağlanırken karşılaşılan Checksum hataları, eksik araba modları ve Content Manager online ayarları.',
    },
  },
  {
    id: 'ffb-direksiyon-ayarlari',
    slug: 'direksiyon-seti-ve-ffb-optimizasyon-rehberi',
    title: 'Direksiyon Seti & Force Feedback (FFB) Optimizasyon Rehberi',
    game: 'Assetto Corsa & BeamNG',
    gameCode: 'genel',
    category: 'Donanım & Ayarlar',
    forumCategory: 'Donanım / Direksiyon Setleri & Simülasyon Ekipmanları',
    time: '15 dk okuma',
    difficulty: 'İleri Seviye',
    coverImage: '/media/images/cm-csp-preview.jpg',
    summary: 'Logitech G29/G920/G923, Thrustmaster T300RS ve Fanatec setler için LUT kalibrasyonu, clipping engelleme ve gerçekçi yol direnci ayarları.',
    highlights: ['LUT Kalibrasyonu', 'Clipping Önleme', 'FFB Post-Processing', 'Gerçekçi Yol Hissi'],
    targetPath: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\assettocorsa\\system\\cfg\\myLUT.lut',
    isActive: true,
    author: {
      name: 'Zecution Gaming 👑',
      role: 'Kurucu',
      badge: 'KURUCU',
      avatar: '/media/images/logo.jpg',
      posts: '148 Gönderi',
    },
    stats: {
      views: '8.9k Görüntülenme',
      likes: 470,
      replies: 38,
      date: 'Ekim 2026',
    },
    requirements: [
      'Logitech G HUB veya Thrustmaster Control Panel',
      'WheelCheck programı',
      'LUTGenerator programı',
      'Content Manager kurulu Assetto Corsa',
    ],
    steps: [
      {
        stepNumber: 1,
        title: 'Direksiyon Sürücüsünü Yapılandırın',
        description: 'Logitech G HUB veya Thrustmaster Control Panel uygulamasını açın. Çalışma açısını 900 dereceye ayarlayın. Merkezleme yayını (Centering Spring) kapatın veya %0 yapın.',
        tip: 'Centering spring açık kalırsa simülasyonun kendi lastik ağırlığı hissedilmez.',
      },
      {
        stepNumber: 2,
        title: 'WheelCheck ile Motor Tepki Testi Yapın',
        description: 'WheelCheck programını yönetici olarak başlatın. Max Count değerini 300 yapın ve Spring Force olarak "Step Log 2" seçin. Direksiyon kendi kendine dönerek motorun lineerlik eğrisini bir CSV dosyası olarak kaydedecektir.',
        tip: 'Test sırasında direksiyona kesinlikle dokunmayın, serbestçe dönmesine izin verin.',
      },
      {
        stepNumber: 3,
        title: 'LUTGenerator ile Özel LUT Dosyası Oluşturun',
        description: 'LUTGenerator programını açın ve WheelCheck’in ürettiği CSV dosyasını seçin. Program motorunuzun ölü bölgesini ve zayıf aralıklarını telafi eden "myLUT.lut" kalibrasyon dosyasını oluşturacaktır.',
        tip: 'Bu dosya dişli motorların orta noktadaki boşluğunu tamamen ortadan kaldırır.',
      },
      {
        stepNumber: 4,
        title: 'LUT Dosyasını Assetto Corsa’ya Ekleyin',
        description: 'Oluşturulan "myLUT.lut" dosyasını "assettocorsa/system/cfg/" klasörünün içine yapıştırın.',
        tip: 'Klasörde aynı isimde dosya varsa üzerine yazın.',
      },
      {
        stepNumber: 5,
        title: 'Content Manager’da FFB Post-Processing’i Açın',
        description: 'Settings > Assetto Corsa > Controls > FFB sekmesine gelin. "Post-Processing" seçeneğini aktif yapın, Type olarak "LUT" ve dosya olarak "myLUT.lut" dosyanızı seçin.',
        tip: 'Gain değerini %80 civarında tutarak clipping yapmasını engelleyin.',
      },
      {
        stepNumber: 6,
        title: 'Yapay Efektleri Kısarak Clipping’i Engelleyin',
        description: 'Kerb FX: %12, Road FX: %10, Slip FX: %8 olarak ayarlayın. FFB Gain oranını %75 - %85 aralığında tutun. Böylece yüksek hızda sert viraj alırken motor zorlanıp detayları kaybetmez.',
        tip: 'Sürüş ekranında sağ alttaki Pedals uygulamasında kırmızı barın tavana vurmamasına dikkat edin.',
      },
    ],
    tips: [
      'Sürüş sırasında sağ alt köşedeki Pedals uygulamasını açın. En sağdaki FFB barı sürekli kırmızı renge ulaşıyorsa direksiyon motorunuz clipping yapıyor demektir; FFB Gain değerini 5-10 puan düşürün.',
      'BeamNG.drive için de FFB Smoothing değerini 120-150 arasına getirerek dişli seslerini azaltabilirsiniz.',
    ],
    troubleshooting: [
      {
        problem: 'Direksiyon düz yolda giderken sağa sola şiddetle sallanıyor (Osilosyon/Wobble).',
        solution: 'Minimum Force değerini %0’a indirin ve Damper Gain değerini %10-15 seviyesine çıkarın.',
      },
    ],
    youtubeVideo: {
      id: '1fU649lM3gU',
      title: 'Direksiyon Seti Force Feedback & LUT Kalibrasyonu Rehberi',
      channel: 'SimRacing Donanım & Rehberler',
      duration: '16:10',
      description: 'Logitech G29/G920 ve Thrustmaster setler için WheelCheck ile LUT tablosu oluşturma, clipping önleme ve gerçekçi direksiyon sertliği ayarları.',
    },
  },
]
